# .github/workflows/ci.yml
name: CI Pipeline

# Define the events that trigger the workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Git, GnuPG, and Curl
      - name: Install Git, GnuPG, and Curl
        run: |
          sudo apt-get update
          sudo apt-get install -y git gnupg curl

      # Step 3: Clone and install zsign
      - name: Install zsign
        run: |
          git clone https://github.com/zhlynn/zsign.git
          cd zsign
          chmod +x INSTALL.sh
          ./INSTALL.sh
          cd build
          sudo cp zsign /usr/local/bin

      # Step 4: Install MongoDB
      - name: Install MongoDB
        run: |
          # Import the public key
          curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor

          # Add the MongoDB repository
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

          # Update packages and install MongoDB
          sudo apt-get update
          sudo apt-get install -y mongodb-org

          # Start MongoDB service
          sudo systemctl start mongod
          sudo systemctl enable mongod

      # Step 5: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Specify the desired Node.js version

      # Step 6: Install npm dependencies
      - name: Install npm Packages
        run: |
          npm install

      # Step 7: Run the Node.js project
      - name: Run Node.js Project
        run: |
          node .
