# azure-pipelines.yml
trigger:
  branches:
    include:
      - master  # Define the branch that will trigger the pipeline

pool:
  vmImage: 'ubuntu-latest' # Change this if you're using a different VM

steps:

# Step 1: Update apt and install dependencies like git, gnupg, and curl
- script: |
    sudo apt-get update
    sudo apt-get install -y git gnupg curl
  displayName: 'Install Git, GnuPG, and Curl'

# Step 2: Clone and install zsign
- script: |
    git clone https://github.com/zhlynn/zsign.git
    cd zsign
    chmod +x INSTALL.sh
    ./INSTALL.sh
    cd build
    sudo cp zsign /usr/local/bin
  displayName: 'Install zsign'

# Step 3: Install MongoDB
- script: |
    # Import the public key
    curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor

    # Add the MongoDB repository
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

    # Update packages and install MongoDB
    sudo apt-get update
    sudo apt-get install -y mongodb-org

    # Start and enable MongoDB service
    sudo systemctl start mongod
    sudo systemctl enable mongod
  displayName: 'Install and Start MongoDB'

# Step 4: Install Node.js using NodeTool task and then install npm dependencies
- task: NodeTool@0
  inputs:
    versionSpec: '16.x' # Specify the desired Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install npm Packages'

# Step 5: Run the Node.js project
- script: |
    node .
  displayName: 'Run Node.js Project'
